create database customer_behaviour;
use customer_behaviour;
select * from customers limit 10;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total 
from customers group by gender order by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customers where discount_applied = "Yes" and purchase_amount > 
(select avg(purchase_amount) as avg_purchase_amt from customers) order by customer_id ;


#-- Q3. Which are the top 5 products with the highest average review rating?
select distinct item_purchased as products, round(avg(review_rating),2) as Average_Product_Rating
from customers group by  item_purchased
order by Average_Product_Rating desc limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) as round
from customers where shipping_type in('Standard', 'Express')
group by shipping_type
order by round;



#--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
#between subscribers and non-subscribers.
select subscription_status, 
	count(customer_id) as total_customers, 
	round(avg(purchase_amount),2) as avg_spend, 
    sum(purchase_amount) as total_revenue
from customers 
group by subscription_status;


#--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 	
	round(sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*)  * 100, 2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc limit 5;



 -- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as 
(select customer_id, previous_purchases,
	case when previous_purchases = 1 then 'New'
		 when previous_purchases between 2 and 10 then 'Returning'
         else 'Loyal'
	end as customer_segment
from customers)

select customer_segment, count(customer_id) as number_of_customers
from cte group by customer_segment
order by customer_segment;



-- Q8. What are the top 3 most purchased products within each category?
with cte as 
(select category, item_purchased, count(item_purchased) as total_orders,
	row_number() over(partition by category order  by count(item_purchased) desc) as item_rank
from customers
group by category, item_purchased
order by category, total_orders desc)
select item_rank, category, item_purchased, total_orders from cte where item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customers 
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group? 
select * from customers limit 10;
select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc; 